name: idwey
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.2+4

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  connectivity_plus: ^2.3.9

  flutter_launcher_icons: "^0.9.2"
  get_it: ^7.2.0
  flutter_spinkit: ^5.1.0
  flutter_hooks: ^0.18.0
  flutter_svg: ^2.0.2
  flutter_bloc: ^8.0.0
  freezed: ^2.3.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  auto_route: ^7.7.1
  firebase_core: ^2.15.0
  cached_network_image: ^3.2.3
  heroicons: ^0.8.0
  dio: ^5.3.1
  dartz: ^0.10.1
  intl: ^0.18.1
  flutter_screenutil: ^5.7.0
  banner_image: ^1.0.7
  readmore: ^2.2.0
  google_maps_flutter: ^2.3.0
  parsed_readmore: ^0.0.6
  flutter_html: ^3.0.0-beta.2
  dots_indicator: ^3.0.0
  shared_preferences: ^2.0.8
  table_calendar: ^3.0.9
  syncfusion_flutter_datepicker: ^23.1.36
  country_picker: ^2.0.21
  jwt_decoder: ^2.0.1
  flutter_typeahead: ^4.0.4
  flutter_rating_bar: ^4.0.1

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  # add the generator to your dev_dependencies
  injectable_generator:
  # add build runner if not already added
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  auto_route_generator: ^7.2.0
  image_picker: ^0.8.4+2
  permission_handler: ^11.0.1


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/inter/static/inter-Black.ttf
        - asset: assets/fonts/inter/static/inter-Bold.ttf
        - asset: assets/fonts/inter/static/inter-ExtraBold.ttf
        - asset: assets/fonts/inter/static/inter-ExtraLight.ttf
        - asset: assets/fonts/inter/static/inter-Light.ttf
        - asset: assets/fonts/inter/static/inter-Medium.ttf
        - asset: assets/fonts/inter/static/inter-SemiBold.ttf
        - asset: assets/fonts/inter/static/inter-Thin.ttf

          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages