part of 'reservation_bloc.dart';

@freezed
class ReservationState with _$ReservationState {
  const factory ReservationState({
    StateStatus? status,
    StateStatus? addToCartStatus,
    String? name,
    String? lastname,
    String? email,
    String? phone,
    String? checkIn,
    String? checkOut,
    bool? available,
    String? totalPrice,
    String? totalPriceOnSale,
    String? nbNights,
    int? guests,
    String? activityDuration,
    String? id,
    String? url,
    String? title,
    String? address,
    String? typeHost,
    String? salePrice,
    String? perPerson,
    int? minNuits,
    String? price,
    String? errorText,
    List<int>? selectedRooms,
    List<Room>? selectedRoomsObject,
    List<Room>? availableChalet,
    List<ExtraPrice>? extraPrice,
  }) = _ReservationState;

  factory ReservationState.initial() => ReservationState(
        status: StateStatus.init,
        addToCartStatus: StateStatus.init,
        name: "",
        lastname: "",
        email: "",
        phone: "",
        checkIn: DateFormat('dd/MM/yyyy').format(DateTime.now()),
        checkOut: DateFormat('dd/MM/yyyy')
            .format(DateTime.now().add(Duration(days: 1))),
        available: false,
        totalPrice: "",
        nbNights: "0",
        guests: 1,
        activityDuration: "",
        id: "",
        url: "",
        title: "",
        address: "",
        typeHost: "",
        salePrice: "",
        perPerson: "",
        minNuits: 0,
        price: "",
        errorText: "",
        totalPriceOnSale: "",
        selectedRooms: [],
        selectedRoomsObject: [],
        extraPrice: [],
        availableChalet: [],
      );
}
